#!/bin/sh

case "$1" in
	start)
		if [ -x /usr/bin/waybeam ]; then
			echo "Skipping vendor modules; Waybeam will load CV610 modules..."
			exit 0
		fi
		echo "Loading vendor modules..."
		vendor=$(ipcinfo -v)
		load_"$vendor" -i
		;;

	stop)
		;;

	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac
